export const uiCopy = {
  zh: {
    meta: {
      description: "Maple 的作品集与随笔：AI 应用、Agent 系统与交互实验",
    },
    nav: {
      open: "打开菜单",
      close: "关闭菜单",
      home: "Maple 首页",
      replay: "重播构建",
      mainNav: "主导航",
      progress: "页面进度",
      langAction: "EN",
      langActionAria: "Switch to English",
    },
    rail: {
      top: { label: "首页", navLabel: "关于我" },
      projects: { label: "作品", navLabel: "作品" },
      stack: { label: "技术栈", navLabel: "技术栈" },
      contact: { label: "文章与联系", navLabel: "文章 / 联系" },
    },
    hero: {
      eyebrowSuffix: "作品集与随笔 2026",
      roleLines: ["创意型工程师", "AI 应用与 Agent 系统"],
      viewWorks: "查看作品",
    },
    journey: {
      title: "我的项目",
      dragHint: "拖动以旋转",
      pauseAria: "暂停项目环自动旋转",
      resumeAria: "继续项目环自动旋转",
      sectionAria: "项目与技术栈",
      ringAria: "可拖拽旋转的项目环",
      openProjectAria: (title) => `打开 ${title} 项目`,
      projectVisualAlt: (title) => `${title} 项目视觉`,
      viewProject: "查看项目",
      handoffFrom: "从想法到项目的路上",
      handoff: { before: "技术让", accent1: "创意", middle: "变成", accent2: "现实" },
      stackAria: "技术栈与能力",
    },
    contact: {
      eyebrow: "ARTICLES / CONTACT / 04",
      titleLine1: "做点有意思的",
      titleLine2: "让技术，跟上想法",
      note: "很多项目的开始，往往只是一个让我感到好奇的问题。我更相信好奇心，而不是一条固定的技术路线。灵感出现时，先让它自由生长；技术不够，就继续学习，直到它拥有可以落地的形状。",
      writingTitle: "读读我的想法",
      linksTitle: "联系我",
      channelsAria: "联系渠道",
      backTop: "BACK TO TOP",
    },
    reader: {
      backHome: "返回主页",
      closeArticle: "关闭文章",
      backToProjects: "返回项目环",
      chapters: "章节导航",
      expand: "展开",
      collapse: "收起",
      projectChaptersAria: (title) => `${title} 项目章节`,
      enlargeImageAria: (alt) => `放大图片：${alt || "文章插图"}`,
      imagePreviewAria: (alt) => (alt ? `图片预览：${alt}` : "图片预览"),
      closePreview: "关闭图片预览",
      loadErrorTitle: "正文暂时未能加载。",
      loadErrorBody: "请检查网络连接后重试。",
      loadErrorRetry: "重新加载正文",
    },
    notFound: {
      titleLine1: "这里没有",
      titleLine2: "可抵达的轨道。",
      body: "这个地址不存在，或者对应的文章与项目已被移动或删除。",
      action: "返回首页",
      homeAria: "返回 Maple 首页",
    },
    boot: {
      progressAria: "Vibe 启动进度",
    },
    wechat: {
      dialogAria: "微信二维码",
      closeAria: "关闭微信二维码",
      qrAlt: (label) => `微信 ${label} 的二维码`,
      idLabel: "微信号",
    },
    intro: {
      regionAria: "Vibe Coding 开场演示",
      cmdAria: "Vibe Coding CMD 记录",
      commandInputAria: (command) => `输入演示命令：${command}`,
      runCommand: "运行命令",
      thesisLead: "你是否厌倦了",
      thesisStrong: "无止境的无效交流？",
      promiseLead: "约束、检查点、验证 无需你考虑",
      promise: { line1: "我帮你", before: "把", accent1: "想法", middle: "变成", accent2: "项目" },
      thesisActionAria: "执行 clear、revert 和 /new，继续演示",
      badCopyLine1: "设计、开发与 AI 实验。",
      badCopyLine2: "把模糊想法做成可以使用的界面。",
      commandLabels: {
        clear: "清空错误输出",
        revert: "回到错误链之前",
        newChat: "开启无污染上下文",
        gitPush: "发布正确链路",
      },
    },
    seed: {
      triggerAria: (seed) => `当前三体初始方向 seed 为 ${seed}，点击修改`,
      inputAria: "输入用于定义三体初始方向的 seed",
    },
  },
  en: {
    meta: {
      description: "Maple's portfolio and notes: AI applications, agent systems, and interactive experiments",
    },
    nav: {
      open: "Open menu",
      close: "Close menu",
      home: "Maple home",
      replay: "Replay build",
      mainNav: "Main navigation",
      progress: "Page progress",
      langAction: "中文",
      langActionAria: "切换到中文",
    },
    rail: {
      top: { label: "Home", navLabel: "About" },
      projects: { label: "Projects", navLabel: "Projects" },
      stack: { label: "Stack", navLabel: "Stack" },
      contact: { label: "Notes & Contact", navLabel: "Notes / Contact" },
    },
    hero: {
      eyebrowSuffix: "PORTFOLIO & NOTES 2026",
      roleLines: ["AI Applications & Agent Systems"],
      viewWorks: "View Projects",
    },
    journey: {
      title: "My Projects",
      dragHint: "Drag to rotate",
      pauseAria: "Pause project ring auto-rotation",
      resumeAria: "Resume project ring auto-rotation",
      sectionAria: "Projects and tech stack",
      ringAria: "Draggable rotating project ring",
      openProjectAria: (title) => `Open project ${title}`,
      projectVisualAlt: (title) => `${title} project visual`,
      viewProject: "View Project",
      handoffFrom: "From idea to project",
      handoff: { before: "Technology turns ", accent1: "ideas", middle: " into ", accent2: "reality" },
      stackAria: "Tech stack and capabilities",
    },
    contact: {
      eyebrow: "ARTICLES / CONTACT / 04",
      titleLine1: "Make something interesting;",
      titleLine2: "let technology keep up with ideas",
      note: "Many projects begin as nothing more than a question that makes me curious. I trust curiosity more than any fixed technical route. When an idea shows up, I let it grow freely first; if my skills fall short, I keep learning until the idea has a shape that can land.",
      writingTitle: "Read my notes",
      linksTitle: "Contact",
      channelsAria: "Contact channels",
      backTop: "BACK TO TOP",
    },
    reader: {
      backHome: "Back to Home",
      closeArticle: "Close article",
      backToProjects: "Back to Projects",
      chapters: "Contents",
      expand: "Expand",
      collapse: "Collapse",
      projectChaptersAria: (title) => `${title} chapters`,
      enlargeImageAria: (alt) => `Enlarge image: ${alt || "article illustration"}`,
      imagePreviewAria: (alt) => (alt ? `Image preview: ${alt}` : "Image preview"),
      closePreview: "Close image preview",
      loadErrorTitle: "The content couldn't be loaded.",
      loadErrorBody: "Check your connection and try again.",
      loadErrorRetry: "Reload content",
    },
    notFound: {
      titleLine1: "There's no orbit",
      titleLine2: "that reaches here.",
      body: "This address doesn't exist, or the article or project it pointed to has been moved or deleted.",
      action: "Back to Home",
      homeAria: "Back to Maple home",
    },
    boot: {
      progressAria: "Vibe startup progress",
    },
    wechat: {
      dialogAria: "WeChat QR code",
      closeAria: "Close WeChat QR code",
      qrAlt: (label) => `WeChat QR code for ${label}`,
      idLabel: "WeChat ID",
    },
    intro: {
      regionAria: "Vibe Coding opening demo",
      cmdAria: "Vibe Coding CMD transcript",
      commandInputAria: (command) => `Type the demo command: ${command}`,
      runCommand: "Run command",
      thesisLead: "Tired of",
      thesisStrong: "endless, fruitless back-and-forth?",
      promiseLead: "Constraints, checkpoints, verification — leave them to me",
      promise: { line1: "I'll turn your", before: "", accent1: "ideas", middle: " into ", accent2: "projects" },
      thesisActionAria: "Run clear, revert and /new to continue the demo",
      badCopyLine1: "Design, development & AI experiments.",
      badCopyLine2: "Turning vague ideas into usable interfaces.",
      commandLabels: {
        clear: "Clear the error output",
        revert: "Back to before the error chain",
        newChat: "Open a clean context",
        gitPush: "Publish the correct pipeline",
      },
    },
    seed: {
      triggerAria: (seed) => `Current three-body seed is ${seed}; click to change`,
      inputAria: "Enter a seed that defines the three-body initial state",
    },
  },
};
